name: Deploy Docker App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_apache:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to deployment folder
        run: |
          DEST=/var/www/html/yourproject
          sudo cp -r ./* $DEST